import './globals.scss'
import React from "react";
import { Sidebar } from '@/component/Sidebar/Sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Sidebar/>
        {children}
        </body>
    </html>
  )
}